name: Tests

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: Tests Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: cargo test
     # - name: cargo test
     #   uses: clechasseur/rs-cargo@v1
     #   with:
     #     command: test
